[mksite]
#init_dir = "where you put mksite/init"

[sidebar]
#course_number = "CS NNN"
#course_name = "your course name"
files
[publish]
cmd = "rsync" # add git?
src_dir = "./publish"
dst_url = "your site URL"
